#!/bin/sh

# clean up cache and all produced files
rm -rf Makefile.in aclocal.m4 autom4te.cache configure depcomp install-sh missing config.guess config.sub ltmain.sh

# reconfiguration steps
#libtoolize -f -c
aclocal
autoconf
automake -a -c --no-force

