//#pragma once
#ifndef __MED_MACROS_OFF_HPP_INCLUDED__
#define __MED_MACROS_OFF_HPP_INCLUDED__
#undef __MED_MACROS_ON_HPP_INCLUDED__

#undef MED_BIT_MASK

#undef MED_BIT_ACCESS_DEF
#undef MED_BIT_ACCESS_DEF_1
#undef MED_BIT_ACCESS_DEF_2
#undef MED_BIT_ACCESS_DEF_3
#undef MED_BIT_ACCESS_DEF_4
#undef MED_BIT_ACCESSOR

#undef MED_BITS_ACCESS_DEF
#undef MED_BITS_ACCESS_DEF_2
#undef MED_BITS_ACCESS_DEF_3
#undef MED_BITS_ACCESS_DEF_4
#undef MED_BITS_ACCESS_DEF_5
#undef MED_BITS_ACCESSOR

#undef MED_BITS_ACCESSOR_MASK


#endif //__MED_MACROS_OFF_HPP_INCLUDED__
